import React from 'react'
import { Link } from 'react-router'
import './legalPage.scss'

const TermsOfService = () => {
    return (
        <div className="legal-page">

            <nav className="legal-navbar">
                <Link to="/" className="legal-navbar__brand">
                    <span className="legal-navbar__dot"></span>
                    InterviewAI
                </Link>
            </nav>

            <div className="legal-content">
                <h1>Terms of Service</h1>
                <p className="legal-updated">Last updated: July 2026</p>

                <h2>Using our service</h2>
                <p>InterviewAI provides AI-generated interview preparation content based on the resume and job description you provide. This content is for preparation purposes only and does not guarantee interview success.</p>

                <h2>Your account</h2>
                <ul>
                    <li>You must provide accurate information when registering</li>
                    <li>You are responsible for keeping your password secure</li>
                    <li>One account per person</li>
                </ul>

                <h2>Acceptable use</h2>
                <p>You agree not to misuse the service, including attempting to overload our AI generation system, sharing your account, or uploading content that isn't yours.</p>

                <h2>AI-generated content</h2>
                <p>Interview questions, answers, and preparation plans are generated by AI and may occasionally contain inaccuracies. Always use your own judgment when preparing for an actual interview.</p>

                <h2>Termination</h2>
                <p>You may delete your account at any time from your account settings. We may suspend accounts that violate these terms.</p>

                <h2>Questions</h2>
                <p>For any questions about these terms, visit our <Link to="/contact">contact page</Link>.</p>

                <Link to="/" className="legal-back-link">← Back to Home</Link>
            </div>

        </div>
    )
}

export default TermsOfService